export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const LOAD_CHANNELS = "LOAD_CHANNELS";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";